#ifndef RAY_H
#define RAY_H

#include "Vector.h"
#include "RayContext.h"

struct Ray
{
    Point origin;
    Vector direction;

    // Context data used in Geometry::intersect()
    // Note:
    //    - This member should be initialized to NULL when generated by the camera
    //    - This member should be copied to the reflected ray when a new ray object is generated
    //    - Do not modify this member elsewhere unless you know what you're doing
    RayContext context;

    Ray(const Point &origin, const Vector &direction) 
        : origin(origin), direction(direction), context(RayContext())
    {
    }

    Point getPoint(float distance) const
    {
        return origin + direction * distance;
    }
};

#endif
